### ISSUE TITLE
core_config_data row deletion when upgrading

### ISSUE THREAD

**Issue by crazylink** [Fintecture/magento#16]
Magento 2.3.5-p2
Fintecture payment v1.2.2

Hi,
When upgrading the extension, some rows disappear from core_config_data table.
After some tests i have found that the following rows of UpgradeData.php file : 

$connection->delete($coreConfigData, ['value' => 'payment/fintecture/fintecture_pis_url_sandbox']);
$connection->delete($coreConfigData, ['value' => 'payment/fintecture/fintecture_oauth_url_sandbox']);
$connection->delete($coreConfigData, ['value' => 'payment/fintecture/fintecture_connect_url_sandbox']);
$connection->delete($coreConfigData, ['value' => 'payment/fintecture/fintecture_oauth_url_production']);
$connection->delete($coreConfigData, ['value' => 'payment/fintecture/fintecture_pis_url_production']);
$connection->delete($coreConfigData, ['value' => 'payment/fintecture/fintecture_connect_url_production']);

are translated to the following query by Magento : 

DELETE FROM `core_config_data` WHERE (value)

400 rows has been deleted from our core_config_data table so i let you imagine if we have installed it on production...

Could you fix it quickly ?

Regards.

**Comment by hugofintecture** [comment]
Thank you for your report, we are currently deleting these migration files that are obsolete and we'll do new releases today. Sorry for the inconvenience.

**Comment by hugofintecture** [comment]
We've just release new releases with some instructions to update: https://github.com/Fintecture/magento/releases.
The problematic scrips have been deleted from the releases.

Thank you again for your report and your time!
