### ISSUE TITLE
Magento 2.3 error when compiling

### ISSUE THREAD

**Issue by zimbar** [Fintecture/magento#25]
Hy

I have cloned branch magento2.3 and i have this error when compiling on magento 2.3

Class Magento\Quote\Model\SubmitQuoteValidator does not exist           

Thanks

**Comment by hugofintecture** [comment]
Hi!

Maybe you can try to clear all cache folders (**generated** folder particulary) and retry compilation with `php bin/magento setup:di:compile`?

Please let me know

**Comment by hugofintecture** [comment]
Ok so this class seems to have been added after 2.3.2 release: https://github.com/magento/magento2/commits/2.3/app/code/Magento/Quote/Model/SubmitQuoteValidator.php.

Last patch version of 2.3 is 2.3.7-p2. Maybe you can update your Magento base?

**Comment by hugofintecture** [comment]
Thank you, please let us know!

**Comment by hugofintecture** [comment]
@zimbar Hi! Any news?

**Comment by hugofintecture** [comment]
Closing this issue related to Magento version. Please reopen if the problem persists.
