### ISSUE TITLE
No redirect to Fintecture after a cancellation

### ISSUE THREAD

**Issue by magentix** [Fintecture/magento#26]
Hello,

I reproduce this issue on my local and pre-production environment. The browser is Firefox.

1. On payment step, the customer select the Fintecture payment method and valid the order.

![etape1](https://user-images.githubusercontent.com/346889/160136580-166ca40f-7b68-4f7c-b1aa-6fb8aa2ba8e6.png)

2. The customer is redirect to Fintecture.
3. The customer cancel the payment with the link on top right. The customer is redirect to Magento on the payment page.
4. The customer select the Fintecture payment method and valid the order.
5. The customer stay on success page with an order complete message.

![etape2](https://user-images.githubusercontent.com/346889/160136955-c9e8815b-a1ba-4ca6-a60b-2f5fb623b958.png)

The order status is "pending payment".

**Comment by hugofintecture** [comment]
Hello,
What is your version of Magento, of PHP and the Fintecture module please?
Thanks!

**Comment by magentix** [comment]
Hi,

- Magento 2.4.2-p2
- PHP 7.4.28

The first request I get the redirect URL to finecture. In the second request, the response is empty... But the Redirect URL appear in the Fintecture log.

![fintecture](https://user-images.githubusercontent.com/346889/160142415-21dfd20d-932d-4e89-8a92-f368e29eeffe.png)

**Comment by magentix** [comment]
Hello,

I don't know why, now I always get the following response from the API:

```
Array
(
    [status] => 401
    [code] => unauthorized
    [log_id] => 98dc7882-0a49-422a-ba0d-9536127ec0d4
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => invalid_redirect_uri
                    [title] => Invalid Redirect URL
                    [message] => Invalid app redirect URL.
                )

        )

)
```

Regards,
Matthieu

**Comment by hugofintecture** [comment]
Hello Mathieu,

Have you created a Magento app in the console and not a custom/SDK app ?

Thanks!

**Comment by hugofintecture** [comment]
Hello @magentix! Have you been able to check your Fintecture app?

**Comment by hugofintecture** [comment]
Hi @magentix! Could you try to add /fr in the URL provided in your app on the Fintecture console and retry please?

**Comment by magentix** [comment]
Hi @hugofintecture,

Yes it works now with "fr" at the end of the URL. We will do some testing next week. Thanks a lot.

**Comment by hugofintecture** [comment]
Perfect! I close the issue so don't hesitate to repoen if needed.
