### ISSUE TITLE
Need a CSP file : csp_whitelist.xml

### ISSUE THREAD

**Issue by eBusinessAtlantique** [Fintecture/magento#65]
Hello
The module is not compatible as it is.
It needs a csp_whitelist.xml file in etc folder.
Best regards,
Maxime

**Comment by hugofintecture** [comment]
Hello,
I suppose that your shop CSP policy is configured in "restrict" mode?
So you don't see our images on the checkout side, right?

Best regards,
Hugo

**Comment by eBusinessAtlantique** [comment]
Hello
No, it is a standard mode for M2.
See here
https://developer.adobe.com/commerce/php/development/security/content-security-policies/
Best regards
Maxime

**Comment by hugofintecture** [comment]
Thanks but what is exactly the problem you encounter without this file please?

I saw that you reported this error "FintectureLogger.ERROR: Redirection error {"exception":"[object] (Exception(code: 0): Error - Status code 401: Invalid app redirect URL" but it's related to your shop configuration in the Fintecture console.
This error is not related to the CSP file.

**Comment by eBusinessAtlantique** [comment]
The error is that there is no CSP configured to allow assets from fintecture.

**Comment by eBusinessAtlantique** [comment]
Like this 
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://assets.fintecture.com/img/new-checkout/magento/banks-select-your-bank.gif (« img-src »).
and this
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://assets.fintecture.com/img/new-checkout/magento/fintecture.svg (« img-src »).
and this
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à https://connect-v2-sbx.fintecture.com/v2/5e3ce649-9aa2-41d0-b533-1eedf488313a (« form-action »).

**Comment by hugofintecture** [comment]
Thank you very much for the details. I understand the problem correctly now. Let me check that and do a new release :)

**Comment by hugofintecture** [comment]
I've done a new release (2.1.2) with this file. Tested it successfully. Available now on GitHub and in next few hours on the Magento composer repo. Thanks again.

**Comment by hugofintecture** [comment]
Module is available now on the composer repo.

**Comment by hugofintecture** [comment]
@eBusinessAtlantique have you been able to test the new release? Thanks in advance.

**Comment by eBusinessAtlantique** [comment]
Hello, new release works fine out of the box. We have just modified CSS when the checkout design has not a white background. Because your design is adding labels with white around it.

**Comment by hugofintecture** [comment]
Thanks for the update. I'll check your second point to see if we can do something about it. Thanks again.
